force-app/main/default/objects/Crypto_Order__c/Crypto_Order__c.object-meta.xml
<CustomObject>
    <label>Crypto Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Crypto Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crypto Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Crypto_Order__c/fields/CreatedOn__c.field-meta.xml
<CustomField>
    <fullName>CreatedOn__c</fullName>
    <label>CreatedOn</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Crypto_Order__c/fields/Market_Price__c.field-meta.xml
<CustomField>
    <fullName>Market_Price__c</fullName>
    <label>Market Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Crypto_Order__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Crypto_Order__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Crypto Orders</relationshipLabel>
    <relationshipName>Crypto_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Crypto_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CoinListCallout.cls
public with sharing class CoinListCallout {
  @AuraEnabled
  public static Object makeGetCallout(String url) {
    Http http = new Http();
    HttpRequest request = new HttpRequest();
    request.setEndpoint(url);
    request.setMethod('GET');

    HttpResponse response = http.send(request);
    Object result = (Object) JSON.deserializeUntyped(response.getBody());
    return result;
  }

  @AuraEnabled
  public static List<Portfolio__c> retrievePortfolios() {
    List<Portfolio__c> portfoliosList = [
      SELECT
        Id,
        Name,
        (
          SELECT Id, CreatedDate, Name__c, Market_Price__c, Quantity__c
          FROM Crypto_Orders__r
          ORDER BY CreatedOn__c DESC
        )
      FROM Portfolio__c
    ];

    return portfoliosList;
  }
}